### ISSUE TITLE
Python3截图问题

### ISSUE THREAD

**Issue by wodeta33** [GoverSky/HTMLTestRunner_cn#12]
说明文档中提到：
> 在python3 中因为unittest运行机制变动，在使用setUp/tearDown中初始化/退出driver时，会出现用例执行失败没有截图的问题，所以推荐使用样例中setUpClass/tearDownClass的用法

如果想在setUp/tearDown中初始化/退出driver可以截图，这个问题有什么办法解决吗？我使用setUpClass/tearDownClass的用法，当一个类里面有多个用例时，截到的图是不准确的，并不是在失败位置的截图。

**Comment by GoverSky** [comment]
有一种办法是自定义方法 校验结果手动添加截图，样例里面有差不多的操作，脑洞不够没想到太好的办法。

**Comment by wodeta33** [comment]
> 有一种办法是自定义方法 校验结果手动添加截图，样例里面有差不多的操作，脑洞不够没想到太好的办法。

好吧，感谢！
