### ISSUE TITLE
html报告统计总数有问题

### ISSUE THREAD

**Issue by tahitimoon** [GoverSky/HTMLTestRunner_cn#17]
非常感谢您分享的代码，感觉非常实用，发现一个小问题。生成的html报告，总数里面没有统计“跳过用例”，如：执行6个用例，1个错误，2个通过，3个跳过，"所有[3]"中只显示了3，照理说应该有6个，跳过的没统计上
![image](https://user-images.githubusercontent.com/37645552/81091935-79a1b900-8f32-11ea-9bbf-b1cc435d4469.png)

**Comment by GoverSky** [comment]
当时做的时候跳过的用例没计入统计，想加上可以把注释去掉
![image](https://user-images.githubusercontent.com/16715284/81136125-388ac280-8f8d-11ea-8110-7ac88fbc0c9c.png)

**Comment by jizhan1989** [comment]
+result.skip_count有两处注释，都要去掉吗？900多行还有一处注释

**Comment by GoverSky** [comment]
改了点东西，自己康康吧
