### ISSUE TITLE
bug  AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by brianlaibaoqin** [GoverSky/HTMLTestRunner_cn#2]
D:\Anaconda\python.exe D:/xinjian/run_this.py
<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<unittest.suite.TestSuite tests=[<testcase1.Test_ranzhi testMethod=test_case1>]>]>]>
E  test_case1 (testcase1.Test_ranzhi)
Traceback (most recent call last):
  File "D:/xinjian/run_this.py", line 23, in <module>
    run.run(discover)
  File "D:\xinjian\common\HTMLTestRunner_jpg.py", line 746, in run
    test(result)
  File "D:\Anaconda\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\Anaconda\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\Anaconda\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\Anaconda\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\Anaconda\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "D:\Anaconda\lib\unittest\suite.py", line 122, in run
    test(result)
  File "D:\Anaconda\lib\unittest\case.py", line 653, in __call__
retesting... 1
    return self.run(*args, **kwds)
  File "D:\Anaconda\lib\unittest\case.py", line 624, in run
    result.stopTest(self)
  File "D:\xinjian\common\HTMLTestRunner_jpg.py", line 659, in stopTest
    if doc.find('_retry')!=-1:
AttributeError: 'NoneType' object has no attribute 'find'

Process finished with exit code 1

**Comment by brianlaibaoqin** [comment]
用HTML 运行  以下代码。出现以上bug 。
# coding=utf-8
from selenium import webdriver
import unittest



class Test_ranzhi(unittest.TestCase):

    url = 'http://laibaoqin.top/ranzhi/www'
    user = 'admin'
    password = 12345678


    @classmethod
    def setUpClass(cls):
        cls.driver = webdriver.Firefox()

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()

    def test_case1(self):
        pass
        self.driver.maximize_window()
        self.driver.implicitly_wait(30)
        self.driver.get(url)
        text = self.driver.find_element_by_css_selector(".btn").text
        print(text)
        if text != "繁體":  # 选择系统语言
            self.driver.find_element_by_css_selector(".btn").click()
            self.driver.find_element_by_xpath("//*[text()='繁體']").click()

        self.driver.find_element_by_css_selector("#account").send_keys(user)
        self.driver.find_element_by_css_selector("#password").send_keys(password)
        self.driver.find_element_by_xpath("//*[@id='keepLoginon']").click()
        self.driver.find_element_by_css_selector('#submit').click()

        try:
            act_name = self.driver.find_elements_by_css_selector(".nav.navbar-nav>li>a")[0].text
            print(act_name)
            assert act_name == "admin"
        except Exception as e:
            print("验证出错了", e)

        print("11111113")
        self.assertEqual(1 ,2)

**Comment by brianlaibaoqin** [comment]
python3

**Comment by brianlaibaoqin** [comment]
self.driver.find_element_by_css_selector("#account").send_keys(user)
    self.driver.find_element_by_css_selector("#password").send_keys(password)   有参数化的 报AttributeError: 'NoneType' object has no attribute 'find'  ，请看看 ！

**Comment by GoverSky** [comment]
没重现啊，兄弟！你的参数化作用域也不对，下面根本引用不到的，还不如放在class上面

**Comment by GoverSky** [comment]
```python
#-*- coding: utf-8 -*-
from selenium import webdriver
import unittest
import time
url = 'http://laibaoqin.top/ranzhi/www'
user = 'admin'
password = 12345678

class Test_ranzhi(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.driver = webdriver.Firefox()

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()

    def test_case1(self):
        """一个测试用例"""
        self.driver.maximize_window()
        self.driver.implicitly_wait(5)
        self.driver.get(url)
        text = self.driver.find_element_by_css_selector(".btn").text
        print(text)
        if text != "繁體":  # 选择系统语言
            self.driver.find_element_by_css_selector(".btn").click()
            self.driver.find_element_by_xpath("//*[text()='繁體']").click()

        self.driver.find_element_by_css_selector("#account").send_keys(user)
        self.driver.find_element_by_css_selector("#password").send_keys(password)
        self.driver.find_element_by_xpath("//*[@id='keepLoginon']").click()

        self.driver.find_element_by_css_selector('#submit').click()
        time.sleep(1)
        try:
            print(self.driver.find_element_by_class_name('bootbox-body').text)
            self.driver.find_element_by_xpath('//button[@data-bb-handler="ok"]').click()
        except:
            pass
        try:
            act_name = self.driver.find_elements_by_css_selector(".nav.navbar-nav>li>a")[0].text
            print(act_name)
            assert act_name == "admin"
        except Exception as e:
            print("验证出错了", e)

        print("233")
        self.assertEqual(1 ,2)
```

**Comment by brianlaibaoqin** [comment]
![image](https://user-images.githubusercontent.com/34622645/38530305-66f84d72-3c9c-11e8-8605-daed46717d0b.png)
 1， 我发现我的原因在哪里了，就是你的吧！  2，还有一个问题就是retry- 了，没有看到浏览器重新打开，重跑呀。

**Comment by GoverSky** [comment]
1、在teardownClass 中初始化driver 是不会重启浏览器的，一个测试类只执行一次，要每次测试都重启放在setUp和tearDown中初始化和关闭
2、我这不编写备注也没有问题的，不知道你的问什么返回了None，因为本身用的是TestCase的_testMethodDoc，这块再针对改一下~
![image](https://user-images.githubusercontent.com/16715284/38531836-8b226b08-3ca4-11e8-92bd-479265af7b67.png)
