### ISSUE TITLE
怎么可以使代码里的print的log打印出来

### ISSUE THREAD

**Issue by tangtingting** [GoverSky/HTMLTestRunner_cn#3]
代码中使用print打印的信息，无法显示出来，再怎样更改可以打印到一个文本文件中

**Comment by tangtingting** [comment]
嗯嗯，有的时候log比较多的时候，print信息可以打印到一个文件中吗
![image](https://user-images.githubusercontent.com/17755131/38717424-66cd5020-3f19-11e8-9028-0b863107afc9.png)

**Comment by GoverSky** [comment]
一个办法就是屏蔽输出重定向的功能，你试试吧
![image](https://user-images.githubusercontent.com/16715284/38719788-5c453692-3f26-11e8-877d-254d2065dd1c.png)

**Comment by tangtingting** [comment]
嗯嗯，可以输出，谢谢，框架很好用
