### ISSUE TITLE
下载你的示例，无法生成报告

### ISSUE THREAD

**Issue by yufeilai666** [GoverSky/HTMLTestRunner_cn#4]
下载你的示例，放到pycharm建立的项目文件夹中，无法生成报告：
![qq 20180425210334](https://user-images.githubusercontent.com/38725827/39247591-67e0bff8-48cc-11e8-98f2-368e39da7fb3.jpg)

**Comment by GoverSky** [comment]
不要用pycharm自带的测试框架去执行测试
