### ISSUE TITLE
测试详情表单缺少自动换行

### ISSUE THREAD

**Issue by chenfei5201213** [GoverSky/HTMLTestRunner_cn#5]
![image](https://user-images.githubusercontent.com/8575520/39612482-7cb308ec-4f92-11e8-8436-cd5654bbf1fa.png)

感谢楼主分享，解决了我项目中case失败无法重试的问题，非常感谢。

**Comment by GoverSky** [comment]
谢谢支持，已追加换行

**Comment by chenfei5201213** [comment]
客气啦，使用您改写后的htmlrunner，解决了我case失败重试的问题，得谢谢您




在 2018-05-07 09:42:19，"守望at天空" <notifications@github.com> 写道：


谢谢支持，已追加换行
