### ISSUE TITLE
你好，使用appium，做手机端webview自动化，截图功能不太好用

### ISSUE THREAD

**Issue by WindInMay524** [GoverSky/HTMLTestRunner_cn#6]
执行失败都无法自动截图，还会导致进程死在那里没办法往下进行
![image](https://user-images.githubusercontent.com/38344643/40103439-015609fa-5920-11e8-8c94-1f95e93e6717.png)

再增加一列执行成功的截图，展示的会不会更清晰一点

**Comment by GoverSky** [comment]
你先试试直接调用appium的截图方法有没有结果吧，看着像是不支持呢

**Comment by WindInMay524** [comment]
嗯，不支持，没办法截webview中的图

**Comment by GoverSky** [comment]
这就没办法了
