### ISSUE TITLE
报告显示异常

### ISSUE THREAD

**Issue by csw583** [GoverSky/HTMLTestRunner_cn#9]
新版本生成的测试报告,饼图不显示, 点击详情无法展开, 点击截图无法显示, 点击报告其它链接都没效果
用你项目的脚本执行生成的测试报告也是一样的问题
我用的是python3.7.1, 有关系?
![image](https://user-images.githubusercontent.com/29198644/50202444-1cd34c00-0399-11e9-810e-842dea487b47.png)

另外, 代码中的'<>'会报错是不是要替换成'!='?
        if isinstance(e, str):
            # ue = unicode(e.encode('string_escape'))
            if PY3K:
                ue = e
            elif e.find("Error") != -1 or e.find("Exception") <> -1:
                es = e.decode('utf-8', 'ignore').split('\n')
                try:
                    if es[-2].find("\\u") <> -1 or es[-2].find('"\\u') <> -1:
                        es[-2] = es[-2].decode('unicode_escape')
                except Exception:
                    pass
                ue = u"\n".join(es)
            else:
                ue = e.decode('utf-8', 'ignore')
        else:
            ue = e

**Comment by GoverSky** [comment]
哦，抱歉自测不全面，是个bug，js方法里面多写了个单引号 
<> 问题也改了
感谢反馈😁最新提交已修改
